dataset:
  name: folsom
  img_size: 64
model:
  name: dtikmeans
  n_prototypes: 3
  encoder_name: resnet18
  transformation_sequence: identity_color_projective
  curriculum_learning: [150, 400]
training:
  batch_size: 64
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [900]
    update_range: epoch
  n_epoches: 1100
  train_stat_interval: 50
  val_stat_interval: 100
  check_cluster_interval: 100
  seed: 7832
  visualizer_port:
